-- Razvan Performance Lab
-- Supabase Auth + per-user Row Level Security
--
-- This file can be used for a fresh database.
-- If your current authenticated schema is already running, you only need
-- to execute the USER EXERCISES section at the bottom.

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    display_name text not null,
    avatar_emoji text not null default '🏋️',
    created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, display_name)
    values (
        new.id,
        coalesce(
            new.raw_user_meta_data ->> 'display_name',
            split_part(new.email, '@', 1),
            'Athlete'
        )
    )
    on conflict (id) do nothing;

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create table if not exists public.workouts (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    workout_date date not null,
    workout_name text,
    notes text,
    created_at timestamptz not null default now()
);

create index if not exists workouts_user_date_idx
on public.workouts (user_id, workout_date desc);

alter table public.workouts enable row level security;

drop policy if exists "users can read own workouts" on public.workouts;
create policy "users can read own workouts"
on public.workouts
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can insert own workouts" on public.workouts;
create policy "users can insert own workouts"
on public.workouts
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can update own workouts" on public.workouts;
create policy "users can update own workouts"
on public.workouts
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users can delete own workouts" on public.workouts;
create policy "users can delete own workouts"
on public.workouts
for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.workout_sets (
    id bigint generated by default as identity primary key,
    workout_id bigint not null references public.workouts(id) on delete cascade,
    exercise text not null,
    set_number integer not null,
    weight_kg numeric not null,
    reps integer not null,
    rir numeric
);

create index if not exists workout_sets_workout_idx
on public.workout_sets (workout_id);

alter table public.workout_sets enable row level security;

drop policy if exists "users can read own workout sets" on public.workout_sets;
create policy "users can read own workout sets"
on public.workout_sets
for select
to authenticated
using (
    exists (
        select 1
        from public.workouts w
        where w.id = workout_sets.workout_id
          and w.user_id = auth.uid()
    )
);

drop policy if exists "users can insert own workout sets" on public.workout_sets;
create policy "users can insert own workout sets"
on public.workout_sets
for insert
to authenticated
with check (
    exists (
        select 1
        from public.workouts w
        where w.id = workout_sets.workout_id
          and w.user_id = auth.uid()
    )
);

drop policy if exists "users can update own workout sets" on public.workout_sets;
create policy "users can update own workout sets"
on public.workout_sets
for update
to authenticated
using (
    exists (
        select 1
        from public.workouts w
        where w.id = workout_sets.workout_id
          and w.user_id = auth.uid()
    )
)
with check (
    exists (
        select 1
        from public.workouts w
        where w.id = workout_sets.workout_id
          and w.user_id = auth.uid()
    )
);

drop policy if exists "users can delete own workout sets" on public.workout_sets;
create policy "users can delete own workout sets"
on public.workout_sets
for delete
to authenticated
using (
    exists (
        select 1
        from public.workouts w
        where w.id = workout_sets.workout_id
          and w.user_id = auth.uid()
    )
);

create table if not exists public.bodyweight_entries (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    entry_date date not null,
    weight_kg numeric not null,
    notes text,
    created_at timestamptz not null default now(),
    unique (user_id, entry_date)
);

create index if not exists bodyweight_user_date_idx
on public.bodyweight_entries (user_id, entry_date desc);

alter table public.bodyweight_entries enable row level security;

drop policy if exists "users can read own bodyweight" on public.bodyweight_entries;
create policy "users can read own bodyweight"
on public.bodyweight_entries
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can insert own bodyweight" on public.bodyweight_entries;
create policy "users can insert own bodyweight"
on public.bodyweight_entries
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can update own bodyweight" on public.bodyweight_entries;
create policy "users can update own bodyweight"
on public.bodyweight_entries
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users can delete own bodyweight" on public.bodyweight_entries;
create policy "users can delete own bodyweight"
on public.bodyweight_entries
for delete
to authenticated
using (auth.uid() = user_id);

-- ============================================================
-- USER EXERCISES
-- Run this section if you already have the Auth schema installed.
-- ============================================================

create table if not exists public.user_exercises (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    name text not null,
    created_at timestamptz not null default now(),
    unique (user_id, name)
);

create index if not exists user_exercises_user_idx
on public.user_exercises (user_id, name);

alter table public.user_exercises enable row level security;

drop policy if exists "users can read own exercises" on public.user_exercises;
create policy "users can read own exercises"
on public.user_exercises
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users can insert own exercises" on public.user_exercises;
create policy "users can insert own exercises"
on public.user_exercises
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can update own exercises" on public.user_exercises;
create policy "users can update own exercises"
on public.user_exercises
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users can delete own exercises" on public.user_exercises;
create policy "users can delete own exercises"
on public.user_exercises
for delete
to authenticated
using (auth.uid() = user_id);
