-- Razvan Performance Lab
-- Supabase Auth + per-user Row Level Security
--
-- IMPORTANT:
-- If you already created the old starter tables, the easiest path while the
-- app is still new is to run the DROP section below first, then run the rest.
-- If you already have data you want to preserve, migrate it instead of dropping.

-- ============================================================
-- OPTIONAL RESET FOR EARLY DEVELOPMENT
-- ============================================================
-- drop table if exists public.workout_sets cascade;
-- drop table if exists public.workouts cascade;
-- drop table if exists public.bodyweight_entries cascade;
-- drop table if exists public.profiles cascade;

-- ============================================================
-- PROFILES
-- ============================================================

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    display_name text not null,
    avatar_emoji text not null default '🏋️',
    created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create policy "users can read own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

create policy "users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- Automatically create a profile when a Supabase Auth account is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, display_name)
    values (
        new.id,
        coalesce(
            new.raw_user_meta_data ->> 'display_name',
            split_part(new.email, '@', 1),
            'Athlete'
        )
    )
    on conflict (id) do nothing;

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- ============================================================
-- WORKOUTS
-- ============================================================

create table if not exists public.workouts (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    workout_date date not null,
    workout_name text,
    notes text,
    created_at timestamptz not null default now()
);

create index if not exists workouts_user_date_idx
on public.workouts (user_id, workout_date desc);

alter table public.workouts enable row level security;

create policy "users can read own workouts"
on public.workouts
for select
to authenticated
using (auth.uid() = user_id);

create policy "users can insert own workouts"
on public.workouts
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "users can update own workouts"
on public.workouts
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "users can delete own workouts"
on public.workouts
for delete
to authenticated
using (auth.uid() = user_id);

-- ============================================================
-- WORKOUT SETS
-- ============================================================

create table if not exists public.workout_sets (
    id bigint generated by default as identity primary key,
    workout_id bigint not null references public.workouts(id) on delete cascade,
    exercise text not null,
    set_number integer not null,
    weight_kg numeric not null,
    reps integer not null,
    rir numeric
);

create index if not exists workout_sets_workout_idx
on public.workout_sets (workout_id);

alter table public.workout_sets enable row level security;

create policy "users can read own workout sets"
on public.workout_sets
for select
to authenticated
using (
    exists (
        select 1
        from public.workouts w
        where w.id = workout_sets.workout_id
          and w.user_id = auth.uid()
    )
);

create policy "users can insert own workout sets"
on public.workout_sets
for insert
to authenticated
with check (
    exists (
        select 1
        from public.workouts w
        where w.id = workout_sets.workout_id
          and w.user_id = auth.uid()
    )
);

create policy "users can update own workout sets"
on public.workout_sets
for update
to authenticated
using (
    exists (
        select 1
        from public.workouts w
        where w.id = workout_sets.workout_id
          and w.user_id = auth.uid()
    )
)
with check (
    exists (
        select 1
        from public.workouts w
        where w.id = workout_sets.workout_id
          and w.user_id = auth.uid()
    )
);

create policy "users can delete own workout sets"
on public.workout_sets
for delete
to authenticated
using (
    exists (
        select 1
        from public.workouts w
        where w.id = workout_sets.workout_id
          and w.user_id = auth.uid()
    )
);

-- ============================================================
-- BODYWEIGHT
-- ============================================================

create table if not exists public.bodyweight_entries (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    entry_date date not null,
    weight_kg numeric not null,
    notes text,
    created_at timestamptz not null default now(),
    unique (user_id, entry_date)
);

create index if not exists bodyweight_user_date_idx
on public.bodyweight_entries (user_id, entry_date desc);

alter table public.bodyweight_entries enable row level security;

create policy "users can read own bodyweight"
on public.bodyweight_entries
for select
to authenticated
using (auth.uid() = user_id);

create policy "users can insert own bodyweight"
on public.bodyweight_entries
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "users can update own bodyweight"
on public.bodyweight_entries
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "users can delete own bodyweight"
on public.bodyweight_entries
for delete
to authenticated
using (auth.uid() = user_id);
