create table if not exists public.workouts (
    id bigint generated by default as identity primary key,
    workout_date date not null,
    workout_name text,
    notes text,
    created_at timestamptz not null default now()
);

create table if not exists public.workout_sets (
    id bigint generated by default as identity primary key,
    workout_id bigint not null references public.workouts(id) on delete cascade,
    exercise text not null,
    set_number integer not null,
    weight_kg numeric not null,
    reps integer not null,
    rir numeric
);

create table if not exists public.bodyweight_entries (
    id bigint generated by default as identity primary key,
    entry_date date not null unique,
    weight_kg numeric not null,
    notes text,
    created_at timestamptz not null default now()
);

alter table public.workouts enable row level security;
alter table public.workout_sets enable row level security;
alter table public.bodyweight_entries enable row level security;

-- Personal-app starter policies.
-- These allow access through your project's anon key.
-- If the app becomes multi-user, replace them with authenticated-user policies.

create policy "anon workouts all"
on public.workouts
for all
to anon
using (true)
with check (true);

create policy "anon workout_sets all"
on public.workout_sets
for all
to anon
using (true)
with check (true);

create policy "anon bodyweight all"
on public.bodyweight_entries
for all
to anon
using (true)
with check (true);
